name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy_fast_api_on_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Zip tool
        uses: montudor/action-zip@v1
      - name: Install Sqlite, libsqlcipher
        run: | 
          sudo apt-get update -y
          sudo apt-get install -y libssl-dev libsqlcipher-dev sqlcipher python3-venv wget
          sudo apt-get install build-essential tcl
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Create env and install Dependecies
        run:  |
            python3 -m venv env
            source env/bin/activate
            pip3 install -r requirements.txt
            cd env/lib/python3.12/site-packages
            zip -r ${OLDPWD}/code.zip .
            cd ${OLDPWD}
            zip -r code.zip . -x "env/*"
            stat -c %s code.zip
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code --function-name ${{secrets.LAMBDA_ARN}} --zip-file fileb://code.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
